### ISSUE TITLE
Julia Exits when using Zlib

### ISSUE THREAD

**Issue by sreekanthpulagam** [dcjones/Codecs.jl#4]
encoded = encode(Zlib, data)

![untitled](https://f.cloud.github.com/assets/4905528/961159/1162d862-04cc-11e3-83e0-9855adf552ef.jpg)

**Comment by randyzwitch** [comment]
This is so old, I almost don't want to ask...is this still an issue? It's both 32-bit Windows and 0.2, so it almost seems moot at this point.
